### ISSUE TITLE
Feature request - implement caching

### ISSUE THREAD

**Issue by matsmcp** [monsoft/abichecker#3]
To avoid unnecessary load on abuseipdb and to preserve query quota I would like to see a cache function.

I did it on Windows (it reduced the query quota usage with maybe 80%) so it's very effective in my eyes

It was a very simple implementation
- the script checks if a file exists (it uses the ip-address as filename)
- if it exists, it reads the score from the file and return that to the calling function
- if not a query is sent to abuseipdb.
  - The ip-address and score from abusipdb are used to create a new cache file and store the score inside
  - the score from abuseipdb is returned to the calling function

- a scheduled job deletes cache files older than a defined amount of time

I'm not that good at Linux/shellscripts (yet) so I'm not sure if I can implement this myself

**Comment by monsoft** [comment]
Honestly, I've never thought about adding a caching option because my home mail server isn't that busy (only two domains), but it might be worth doing.

Implementing caching in the way you have proposed is quite simple, and may work well on non-busy mail servers (like mine :-) ). For servers which are busy, this may cause quite significant IO load and may require something more sophisticated to store IPs and its scores like SQLite DB or any other DB.

When I will find a time, I will try to add simple caching option to this script.

Thanks

**Comment by matsmcp** [comment]
I agree.

On big server something faster will be needed but I think it can help on small/medium sized servers.
To improve the performance of a file based cache faster you can place it on a ramdrive

**Comment by matsmcp** [comment]
Got a prototype done in https://github.com/matsmcp/abichecker.
I think it should have better file/path checking

**Comment by monsoft** [comment]
Caching has been implemented.
